# Epstein Exposed - Support the Investigation
# These are supported funding model platforms

github: # [lorddreadcoin] - Enable GitHub Sponsors if desired
patreon: originaldankster
ko_fi: # Add if you create one
buy_me_a_coffee: # Add if you create one

# Custom donation links (Venmo, CashApp, Bitcoin)
custom: 
  - https://venmo.com/dankstervisionary
  - https://cash.app/$dankstervision
  - https://blockchair.com/bitcoin/address/bc1qyh3yj9ga7dt2npgvdk2mywxt6krgye249md9ax
