import type { Entity, Connection, Anomaly, SystemMetrics } from './types';

// Generate mock entities for initial visualization
export function generateMockEntities(): Entity[] {
  const entities: Entity[] = [
    // Key persons
    {
      id: 'person-1',
      label: 'Jeffrey Epstein',
      type: 'person',
      position: [0, 0, 0],
      connections: ['person-2', 'person-3', 'location-1', 'location-2'],
      strength: 1.0,
      metadata: {
        role: 'Primary Subject',
        description: 'Convicted sex offender and financier',
        suspicionScore: 1.0,
      },
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    {
      id: 'person-2',
      label: 'Ghislaine Maxwell',
      type: 'person',
      position: [3, 2, 1],
      connections: ['person-1', 'location-1', 'location-3'],
      strength: 0.95,
      metadata: {
        role: 'Associate',
        description: 'British socialite, convicted accomplice',
        suspicionScore: 0.95,
      },
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    {
      id: 'person-3',
      label: 'Prince Andrew',
      type: 'person',
      position: [-3, 1, 2],
      connections: ['person-1', 'location-1'],
      strength: 0.7,
      metadata: {
        role: 'Associate',
        description: 'Duke of York',
        suspicionScore: 0.6,
      },
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    {
      id: 'person-4',
      label: 'Jean-Luc Brunel',
      type: 'person',
      position: [2, -3, 1],
      connections: ['person-1', 'person-2'],
      strength: 0.8,
      metadata: {
        role: 'Associate',
        description: 'French modeling agent',
        suspicionScore: 0.85,
      },
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    {
      id: 'person-5',
      label: 'Les Wexner',
      type: 'person',
      position: [-2, -2, -2],
      connections: ['person-1', 'location-4'],
      strength: 0.6,
      metadata: {
        role: 'Financial Connection',
        description: 'Billionaire businessman',
        suspicionScore: 0.4,
      },
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    // Locations
    {
      id: 'location-1',
      label: 'Little St. James Island',
      type: 'location',
      position: [5, 0, -2],
      connections: ['person-1', 'person-2', 'person-3', 'flight-1'],
      strength: 0.95,
      metadata: {
        description: 'Private island in US Virgin Islands',
        coordinates: { lat: 18.2969, lng: -64.8253 },
        suspicionScore: 1.0,
      },
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    {
      id: 'location-2',
      label: 'NYC Townhouse',
      type: 'location',
      position: [-4, 3, 0],
      connections: ['person-1', 'document-1'],
      strength: 0.85,
      metadata: {
        description: '9 East 71st Street, Manhattan',
        coordinates: { lat: 40.7712, lng: -73.9654 },
        suspicionScore: 0.9,
      },
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    {
      id: 'location-3',
      label: 'Paris Apartment',
      type: 'location',
      position: [1, 4, 3],
      connections: ['person-2', 'person-4'],
      strength: 0.6,
      metadata: {
        description: 'Avenue Foch residence',
        coordinates: { lat: 48.8738, lng: 2.2850 },
        suspicionScore: 0.7,
      },
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    {
      id: 'location-4',
      label: 'New Albany, Ohio',
      type: 'location',
      position: [-5, -1, 2],
      connections: ['person-5', 'person-1'],
      strength: 0.4,
      metadata: {
        description: 'Wexner estate location',
        coordinates: { lat: 40.0812, lng: -82.8088 },
        suspicionScore: 0.3,
      },
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    // Flights
    {
      id: 'flight-1',
      label: 'Lolita Express',
      type: 'flight',
      position: [4, -2, -3],
      connections: ['person-1', 'location-1', 'document-2'],
      strength: 0.9,
      metadata: {
        description: 'Boeing 727 private jet',
        flightDetails: {
          origin: 'Teterboro',
          destination: 'St. Thomas',
          date: new Date('2002-03-15'),
          aircraft: 'Boeing 727-31',
        },
        suspicionScore: 0.95,
      },
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    {
      id: 'flight-2',
      label: 'Flight Log Entry #127',
      type: 'flight',
      position: [3, 3, -2],
      connections: ['person-1', 'person-3'],
      strength: 0.75,
      metadata: {
        flightDetails: {
          origin: 'Palm Beach',
          destination: 'St. Thomas',
          date: new Date('2001-07-22'),
        },
        suspicionScore: 0.8,
      },
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    // Documents
    {
      id: 'document-1',
      label: 'Black Book',
      type: 'document',
      position: [-3, -3, 3],
      connections: ['person-1', 'location-2'],
      strength: 0.85,
      metadata: {
        description: 'Contact book with names and numbers',
        documentCount: 97,
        suspicionScore: 0.9,
      },
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    {
      id: 'document-2',
      label: 'Flight Logs 1995-2013',
      type: 'document',
      position: [0, -4, -1],
      connections: ['flight-1', 'person-1'],
      strength: 0.9,
      metadata: {
        description: 'Complete flight manifests',
        documentCount: 73,
        suspicionScore: 0.95,
      },
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    {
      id: 'document-3',
      label: '2019 Indictment',
      type: 'document',
      position: [-1, 2, -4],
      connections: ['person-1', 'event-1'],
      strength: 0.8,
      metadata: {
        description: 'Federal indictment SDNY',
        suspicionScore: 0.7,
      },
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    // Events
    {
      id: 'event-1',
      label: '2019 Arrest',
      type: 'event',
      position: [0, 5, 0],
      connections: ['person-1', 'document-3'],
      strength: 0.7,
      metadata: {
        date: new Date('2019-07-06'),
        description: 'Arrest at Teterboro Airport',
        suspicionScore: 0.5,
      },
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    {
      id: 'event-2',
      label: '2008 Plea Deal',
      type: 'event',
      position: [-2, 4, -2],
      connections: ['person-1'],
      strength: 0.65,
      metadata: {
        date: new Date('2008-06-30'),
        description: 'Florida state plea agreement',
        suspicionScore: 0.8,
      },
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
    // Transactions
    {
      id: 'transaction-1',
      label: '$46M Transfer',
      type: 'transaction',
      position: [4, 1, 4],
      connections: ['person-1', 'person-5'],
      strength: 0.7,
      metadata: {
        amount: 46000000,
        currency: 'USD',
        description: 'Wexner to Epstein transfer',
        suspicionScore: 0.75,
      },
      createdAt: new Date('2024-01-01'),
      updatedAt: new Date(),
    },
  ];
  
  return entities;
}

export function generateMockConnections(): Connection[] {
  const connections: Connection[] = [
    {
      id: 'conn-1',
      sourceId: 'person-1',
      targetId: 'person-2',
      type: 'associated_with',
      strength: 0.95,
      evidence: ['document-1', 'document-2'],
      discoveredAt: new Date(),
    },
    {
      id: 'conn-2',
      sourceId: 'person-1',
      targetId: 'person-3',
      type: 'associated_with',
      strength: 0.7,
      evidence: ['flight-2'],
      discoveredAt: new Date(),
    },
    {
      id: 'conn-3',
      sourceId: 'person-1',
      targetId: 'location-1',
      type: 'present_at',
      strength: 1.0,
      evidence: ['document-2', 'flight-1'],
      discoveredAt: new Date(),
    },
    {
      id: 'conn-4',
      sourceId: 'person-2',
      targetId: 'location-1',
      type: 'present_at',
      strength: 0.9,
      evidence: ['document-2'],
      discoveredAt: new Date(),
    },
    {
      id: 'conn-5',
      sourceId: 'person-3',
      targetId: 'location-1',
      type: 'present_at',
      strength: 0.6,
      evidence: ['flight-2'],
      discoveredAt: new Date(),
    },
    {
      id: 'conn-6',
      sourceId: 'person-1',
      targetId: 'person-5',
      type: 'financial_link',
      strength: 0.8,
      evidence: ['transaction-1'],
      discoveredAt: new Date(),
    },
    {
      id: 'conn-7',
      sourceId: 'person-2',
      targetId: 'person-4',
      type: 'associated_with',
      strength: 0.85,
      evidence: ['document-1'],
      discoveredAt: new Date(),
    },
    {
      id: 'conn-8',
      sourceId: 'flight-1',
      targetId: 'location-1',
      type: 'present_at',
      strength: 0.95,
      evidence: ['document-2'],
      discoveredAt: new Date(),
    },
    {
      id: 'conn-9',
      sourceId: 'person-1',
      targetId: 'document-1',
      type: 'mentioned_in',
      strength: 1.0,
      evidence: [],
      discoveredAt: new Date(),
    },
    {
      id: 'conn-10',
      sourceId: 'person-1',
      targetId: 'event-1',
      type: 'present_at',
      strength: 1.0,
      evidence: ['document-3'],
      discoveredAt: new Date(),
    },
    // New discovery (highlighted in gold)
    {
      id: 'conn-new-1',
      sourceId: 'person-4',
      targetId: 'location-3',
      type: 'present_at',
      strength: 0.75,
      evidence: [],
      discoveredAt: new Date(),
      isNew: true,
    },
  ];
  
  return connections;
}

export function generateMockAnomalies(): Anomaly[] {
  return [
    {
      id: 'anomaly-1',
      type: 'timeline_conflict',
      severity: 'high',
      title: 'Timeline Inconsistency Detected',
      description: 'Flight log shows departure from Palm Beach at 14:00, but deposition testimony claims subject was in NYC meeting at 13:00 same day.',
      evidence: ['document-2', 'document-3'],
      entities: ['person-1', 'flight-2'],
      hypothesis: 'Either the flight log or deposition contains inaccurate information.',
      confidence: 0.85,
      discoveredAt: new Date(Date.now() - 30000),
      agentId: 'pattern-agent-1',
    },
    {
      id: 'anomaly-2',
      type: 'suspicious_redaction',
      severity: 'critical',
      title: 'Pattern Match: Coordinated Redactions',
      description: '14 documents contain redactions of identical length (47 characters) in similar contextual positions, suggesting systematic concealment.',
      evidence: ['document-1', 'document-3'],
      entities: [],
      hypothesis: 'Redacted content may be a specific name or identifier appearing across multiple documents.',
      confidence: 0.72,
      discoveredAt: new Date(Date.now() - 120000),
      agentId: 'redaction-agent-1',
    },
    {
      id: 'anomaly-3',
      type: 'connection_discovered',
      severity: 'medium',
      title: 'New Entity Connection Found',
      description: 'Cross-reference analysis reveals previously unknown link between Paris apartment and modeling agency records.',
      evidence: [],
      entities: ['person-4', 'location-3'],
      confidence: 0.68,
      discoveredAt: new Date(Date.now() - 300000),
      agentId: 'cross-ref-agent-1',
    },
    {
      id: 'anomaly-4',
      type: 'financial',
      severity: 'high',
      title: 'Unusual Transaction Pattern',
      description: 'Series of wire transfers totaling $46M from Wexner accounts lack standard documentation typically required for transactions of this size.',
      evidence: ['transaction-1'],
      entities: ['person-1', 'person-5'],
      hypothesis: 'Transfers may have been structured to avoid reporting requirements.',
      confidence: 0.79,
      discoveredAt: new Date(Date.now() - 600000),
      agentId: 'pattern-agent-1',
    },
  ];
}

export function generateMockMetrics(): SystemMetrics {
  return {
    documentsProcessed: 2847,
    documentsTotal: 4500,
    entitiesDiscovered: 1243,
    connectionsFound: 8921,
    redactionsAnalyzed: 15672,
    anomaliesDetected: 127,
    activeAgents: 6,
    lastUpdate: new Date(),
  };
}
